name = "theme_name"

[base]
base03 = "#1a1b16"
base02 = "#22231c"
base01 = "#22231c"
base00 = "#22231c"
base0 = "#c5c7bf"
base1 = "#c5c7bf"
base2 = "#c5c7bf"
base3 = "#c5c7bf"

[colors]
yellow = "#ada99d"
orange = "#bd9e9a"
red = "#bd9e9a"
magenta = "#bd9e9a"
violet = "#738683"
blue = "#a6beba"
cyan = "#a6beba"
green = "#acad8c"

[syntax]
comment = "green"
function = "green"
type = "cyan"
keyword = "violet"
constant = "magenta"
string = "green"
parameter = "orange"
property = "blue"

[ui]
accent = "base0"
selection = "#66645e40"
border = "base03"
